name=RC522_UART
version=1.0.0
author=TCL47-Trương Công Lý
maintainer=TCL47-Trương Công Lý
sentence=A library for the RC522 Mini RFID 13.56MHz module with UART interface.
paragraph=This library allows you to interface with the RC522 Mini RFID module via serial UART. It supports reading UIDs, authentication, reading and writing blocks on Mifare Classic cards (1K/4K).
category=Device Control
url=https://github.com/TCL47-GITHUB/RC522_UART
architectures=*
